spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  # cassandra:
  #   keyspace-name: tacocloud
  #   schema-action: RECREATE
  #   port: 9042
  #   local-datacenter: datacenter1


  data:
    mongodb:
      host: localhost
      port: 27017
      database: tacocloud
